package com.assessment.agentic.model;

import java.time.Clock;
import java.time.Duration;
import java.time.Instant;
import java.util.LinkedHashMap;
import java.util.Map;

public class DeterministicModelProvider implements ModelProvider {

    private final Clock clock;

    public DeterministicModelProvider(Clock clock) {
        this.clock = clock;
    }

    @Override
    public ModelProviderType type() {
        return ModelProviderType.DETERMINISTIC;
    }

    @Override
    public ModelResult invoke(ModelRequest request, Duration timeout) {
        Instant start = clock.instant();
        Map<String, String> fields = new LinkedHashMap<>();
        request.requiredFields().forEach((field, description) -> fields.put(field, deterministicValue(request, field, description)));
        String rawOutput = fields.toString();
        return new ModelResult(
            ModelProviderType.DETERMINISTIC,
            "deterministic-template-v1",
            request.schemaName(),
            fields,
            rawOutput,
            request.prompt().length(),
            rawOutput.length(),
            Duration.between(start, clock.instant()),
            null,
            null
        );
    }

    private String deterministicValue(ModelRequest request, String field, String description) {
        return switch (field) {
            case "summary" -> "Deterministic " + request.capability().name().toLowerCase().replace('_', ' ') + " for: "
                + abbreviate(request.prompt(), 160);
            case "status" -> "READY";
            case "riskLevel" -> "LOW";
            case "requiresClarification" -> String.valueOf(request.prompt().toLowerCase().contains("unclear"));
            default -> description + " generated by deterministic provider";
        };
    }

    private String abbreviate(String value, int max) {
        if (value.length() <= max) {
            return value;
        }
        return value.substring(0, max - 3) + "...";
    }
}
