package com.assessment.agentic.model;

public enum ModelCapability {
    REQUIREMENT_ANALYSIS,
    AMBIGUITY_ANALYSIS,
    REPOSITORY_ANALYSIS,
    TASK_DECOMPOSITION,
    ARCHITECTURE,
    IMPLEMENTATION,
    TEST_GENERATION,
    VALIDATION_DIAGNOSIS,
    REPAIR,
    DOCUMENTATION,
    SECURITY_RISK_REVIEW,
    RELEASE_READINESS
}
