package com.assessment.agentic.agents;

public enum AgentRole {
    REQUIREMENT_INTERPRETER,
    AMBIGUITY_ANALYST,
    CODEBASE_ANALYST,
    PLANNER,
    ARCHITECT,
    IMPLEMENTER,
    TEST_ENGINEER,
    VALIDATION_DIAGNOSTICIAN,
    REPAIR_ENGINEER,
    DOCUMENTATION_WRITER,
    SECURITY_REVIEWER,
    RELEASE_REVIEWER
}
